sudo: false
language: python
python: 2.7

branches:
    only:
        - master

matrix:
    fast_finish: true
    include:
        - python: 2.7

        - python: 3.6

install:
    - pip install -r test-requirements.txt

script:
    - make test

cache:
    - pip

notifications:
    email: false

