os: linux
sudo: false
language: python

python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6

install:
    - pip install tox

script:
    - tox

cache:
    - pip

notifications:
    email: false

